services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"


  redis:
    image: redis
    ports:
      - "6379:6379"

  spotlights-routing-gateway:
    image: anupsarkar/spotlights-routing-gateway
    build:
      context: .
      dockerfile: src/Gateway/SpotLights.Routing.Gateway/Dockerfile
    ports:
      - "4000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - ms-course-api
      - ms-quiz-api
      - ms-certification-api
 

  spotlights-portal-app:
    image: anupsarkar/spotlights-portal-application
    build:
      context: .
      dockerfile: src/Microservices/Portal/SpotLights.Portal.Application/Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - sqlserver

  ms-course-api:
    image: anupsarkar/spotlights-course-api
    build:
      context: .
      dockerfile: src/Microservices/Course/SpotLights.Course.Api/Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - sqlserver

  ms-quiz-api:
    image: anupsarkar/spotlights-quiz-api
    build:
      context: .
      dockerfile: src/Microservices/Quiz/SpotLights.Quiz.Api/Dockerfile
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - sqlserver

  ms-certification-api:
    image: anupsarkar/spotlights-certification-api
    build:
      context: .
      dockerfile: src/Microservices/Certification/SpotLights.Certification.Api/Dockerfile
    ports:
      - "5003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - sqlserver

 
